### ISSUE TITLE
UI doesn't launch on Ubuntu 16.04

### ISSUE THREAD

**Issue by lauren-elise-thomas** [psieg/Lightpack#36] opened 2016-05-01 23:39 UTC
The Lightpack lights up but the UI refuses to launch. Neither the Prismatik window or the appindicator appear.

`2016_05_01 18:30:14:565 Prismatik 5.11.2.7
18:30:14:697 Debug: LightpackApplication::LightpackApplication(int&, char**) 
18:30:14:697 Debug: Prismatik: 5.11.2.7 rev. e33a117 
18:30:14:697 Debug: Build with Qt verison: 5.2.1 
18:30:14:697 Debug: Qt version currently in use: 5.5.1 
18:30:14:697 Debug: static bool SettingsScope::Settings::Initialize(const QString&, bool) 
18:30:14:697 Debug: static QString SettingsScope::Settings::getMainConfigPath() "/home/[REDACTED]/.Prismatik/main.conf" 
18:30:14:697 Debug: static QString SettingsScope::Settings::getMainConfigPath() "/home/[REDACTED]/.Prismatik/main.conf" 
18:30:14:698 Debug: static bool SettingsScope::Settings::Initialize(const QString&, bool) debugLevel = 1 
18:30:14:698 Debug: Settings file: "/home/[REDACTED]/.Prismatik/Profiles/Lightpack.ini" 
18:30:14:698 Debug: static void SettingsScope::Settings::initDevicesMap() 
18:30:14:698 Debug: static void SettingsScope::Settings::initCurrentProfile(bool) false 
18:30:14:701 Debug: static void SettingsScope::Settings::initCurrentProfile(bool) led 
18:30:14:706 Debug: SettingsWindow::SettingsWindow(QWidget*) thread id:  0x7fcd1566c740 
18:30:14:873 Debug: void SettingsWindow::initLanguages() 
18:30:14:873 Debug: void SettingsWindow::initVirtualLeds(int) 10 
18:30:14:873 Debug: void SettingsWindow::loadTranslation(const QString&) "<System>" 
18:30:14:873 Debug: static void SettingsScope::Settings::setLanguage(const QString&) 
18:30:14:873 Debug: System locale "en_US" 
18:30:14:873 Debug: static void SettingsScope::Settings::setLanguage(const QString&) 
18:30:14:873 Warning: Fail load translation for locale "en_US" pathToLocale ":/translations/en_US" 
18:30:14:893 Debug: SettingsWindow::SettingsWindow(QWidget*) initialized 
18:30:14:893 Debug: void SettingsWindow::createTrayIcon() 
18:30:14:894 Debug: void SysTrayIconPrivate::createActions() 
18:30:14:895 Debug: static QStringList SettingsScope::Settings::findAllProfiles() 
18:30:14:897 Debug: void SettingsWindow::connectSignalsSlots() 
18:30:14:897 Debug: void LightpackApplication::startLedDeviceManager() 
18:30:14:897 Debug: void LightpackPluginInterface::initColors(int) 10 
18:30:14:897 Debug: void LightpackApplication::startLedDeviceManager() end 
18:30:14:897 Debug: void LightpackApplication::startApiServer() Start API server 
18:30:14:897 Debug: void LedDeviceManager::initLedDevice() 
18:30:14:897 Debug: void ApiServerSetColorTask::setApiDeviceNumberOfLeds(int) 10 
18:30:14:897 Debug: AbstractLedDevice* LedDeviceManager::createLedDevice(SupportedDevices::DeviceType) SupportedDevices::LightpackDevice 
18:30:14:897 Debug: LedDeviceLightpack::LedDeviceLightpack(QObject*) 
18:30:14:897 Debug: LedDeviceLightpack::LedDeviceLightpack(QObject*) thread id:  0x7fcce77fe700 
18:30:14:897 Debug: LedDeviceLightpack::LedDeviceLightpack(QObject*) initialized 
18:30:14:897 Debug: void ApiServer::setInterface(LightpackPluginInterface*) "2.0" 
18:30:14:897 Debug: virtual void LedDeviceLightpack::updateDeviceSettings() LedDeviceManager(0xebf6a0) 
18:30:14:897 Debug: void LedDeviceLightpack::closeDevices() 
18:30:14:897 Debug: void ApiServer::updateApiKey(const QString&) "" 
18:30:14:897 Debug: virtual void LedDeviceLightpack::open() "hid_open(0x1d50, 0x6022)" 
18:30:14:897 Debug: void ApiServer::startListening() 3636 
18:30:14:897 Debug: void LightpackApplication::initGrabManager() 
18:30:14:897 Debug: GrabManager::GrabManager(QWidget*) 
18:30:14:897 Debug: void GrabManager::initGrabbers() 
18:30:14:897 Debug: static int SettingsScope::Settings::getGrabSlowdown() 
18:30:14:897 Debug: static Grab::GrabberType SettingsScope::Settings::getGrabberType() 
18:30:14:898 Debug: GrabberBase* GrabManager::queryGrabber(Grab::GrabberType) grabberType: 2 
18:30:14:898 Debug: static int SettingsScope::Settings::getGrabSlowdown() 
18:30:14:898 Debug: virtual void GrabberBase::setGrabInterval(int) GrabberBase 
18:30:14:898 Debug: void GrabManager::initColorLists(int) 10 
18:30:14:898 Debug: void GrabManager::initLedWidgets(int) 10 
18:30:14:898 Debug: void GrabManager::initLedWidgets(int) First widget initialization 
18:30:14:898 Debug: GrabWidget::GrabWidget(int, QWidget*) 0 
18:30:14:898 Debug: void GrabWidget::settingsProfileChanged() 0 
18:30:14:898 Debug: void GrabManager::initLedWidgets(int) Append 9 grab widgets 
18:30:14:898 Debug: GrabWidget::GrabWidget(int, QWidget*) 1 
18:30:14:899 Debug: void GrabWidget::settingsProfileChanged() 1 
18:30:14:899 Debug: GrabWidget::GrabWidget(int, QWidget*) 2 
18:30:14:899 Debug: void GrabWidget::settingsProfileChanged() 2 
18:30:14:900 Debug: GrabWidget::GrabWidget(int, QWidget*) 3 
18:30:14:900 Debug: void GrabWidget::settingsProfileChanged() 3 
18:30:14:900 Debug: GrabWidget::GrabWidget(int, QWidget*) 4 
18:30:14:901 Debug: void GrabWidget::settingsProfileChanged() 4 
18:30:14:901 Debug: GrabWidget::GrabWidget(int, QWidget*) 5 
18:30:14:901 Debug: void GrabWidget::settingsProfileChanged() 5 
18:30:14:901 Debug: GrabWidget::GrabWidget(int, QWidget*) 6 
18:30:14:902 Debug: void GrabWidget::settingsProfileChanged() 6 
18:30:14:902 Debug: GrabWidget::GrabWidget(int, QWidget*) 7 
18:30:14:902 Debug: found Lightpack, serial number:  "9533131313035160F131" 
18:30:14:902 Debug: virtual void LedDeviceLightpack::open() Lightpack opened 
18:30:14:902 Debug: virtual void LedDeviceLightpack::updateDeviceSettings() LedDeviceManager(0xebf6a0) 
18:30:14:903 Debug: virtual void LedDeviceLightpack::setRefreshDelay(int) 100 
18:30:14:903 Debug: void GrabWidget::settingsProfileChanged() 7 
18:30:14:903 Debug: GrabWidget::GrabWidget(int, QWidget*) 8 
18:30:14:903 Debug: virtual void LedDeviceLightpack::setColorDepth(int) 128 
18:30:14:903 Debug: void GrabWidget::settingsProfileChanged() 8 
18:30:14:903 Debug: GrabWidget::GrabWidget(int, QWidget*) 9 
18:30:14:904 Debug: virtual void LedDeviceLightpack::setSmoothSlowdown(int) 100 
18:30:14:904 Debug: void GrabWidget::settingsProfileChanged() 9 
18:30:14:904 Debug: void GrabManager::updateScreenGeometry() 
18:30:14:904 Debug: void GrabManager::settingsProfileChanged(const QString&) 
18:30:14:904 Debug: void GrabManager::setNumberOfLeds(int) 10 
18:30:14:904 Debug: void GrabManager::initColorLists(int) 10 
18:30:14:904 Debug: void GrabManager::initLedWidgets(int) 10 
18:30:14:904 Debug: void GrabManager::initLedWidgets(int) Remove last 0 grab widgets 
18:30:14:904 Debug: void GrabWidget::settingsProfileChanged() 0 
18:30:14:904 Debug: void GrabWidget::settingsProfileChanged() 1 
18:30:14:904 Debug: virtual void LedDeviceLightpack::requestFirmwareVersion() 
18:30:14:904 Debug: void GrabWidget::settingsProfileChanged() 2 
18:30:14:904 Debug: bool LedDeviceLightpack::readDataFromDevice() 
18:30:14:904 Debug: void GrabWidget::settingsProfileChanged() 3 
18:30:14:904 Debug: virtual void LedDeviceLightpack::requestFirmwareVersion() Version: "0.0" 
18:30:14:904 Debug: void GrabWidget::settingsProfileChanged() 4 
18:30:14:904 Debug: bool LedDeviceLightpack::tryToReopenDevice() Reopen success 
18:30:14:904 Debug: void GrabWidget::settingsProfileChanged() 5 
18:30:14:904 Debug: void GrabWidget::settingsProfileChanged() 6 
18:30:14:904 Debug: virtual void LedDeviceLightpack::setRefreshDelay(int) 100 
18:30:14:904 Debug: void GrabWidget::settingsProfileChanged() 7 
18:30:14:904 Debug: void GrabWidget::settingsProfileChanged() 8 
18:30:14:904 Debug: void GrabWidget::settingsProfileChanged() 9 
18:30:14:904 Debug: GrabManager::GrabManager(QWidget*) initialized 
18:30:14:904 Debug: static bool SettingsScope::Settings::isMoodLampLiquidMode() 
18:30:14:904 Debug: static int SettingsScope::Settings::getMoodLampSpeed() 
18:30:14:904 Debug: static QColor SettingsScope::Settings::getMoodLampColor() 
18:30:14:904 Debug: static int SettingsScope::Settings::getMoodLampSpeed() 
18:30:14:904 Debug: static QColor SettingsScope::Settings::getMoodLampColor() 
18:30:14:904 Debug: static bool SettingsScope::Settings::isMoodLampLiquidMode() 
18:30:14:904 Debug: void MoodLampManager::setLiquidMode(bool) true 
18:30:14:904 Debug: void MoodLampManager::initColors(int) 10 
18:30:14:904 Debug: void SettingsWindow::startBacklight() m_backlightStatus = 1 m_deviceLockStatus = 0 
18:30:14:904 Debug: void LightpackApplication::settingsChanged() 
18:30:14:904 Debug: virtual void LedDeviceLightpack::setColorDepth(int) 128 
18:30:14:904 Debug: void LightpackPluginInterface::changeProfile(QString) "Lightpack" 
18:30:14:904 Debug: void GrabManager::onSendDataOnlyIfColorsEnabledChanged(bool) true 
18:30:14:904 Debug: void MoodLampManager::setSendDataOnlyIfColorsChanged(bool) true 
18:30:14:904 Debug: static QColor SettingsScope::Settings::getMoodLampColor() 
18:30:14:904 Debug: static int SettingsScope::Settings::getMoodLampSpeed() 
18:30:14:904 Debug: void MoodLampManager::setLiquidModeSpeed(int) 50 
18:30:14:904 Debug: static bool SettingsScope::Settings::isMoodLampLiquidMode() 
18:30:14:905 Debug: void MoodLampManager::setLiquidMode(bool) true 
18:30:14:905 Debug: static Lightpack::Mode SettingsScope::Settings::getLightpackMode() 
18:30:14:905 Debug: void GrabManager::start(bool) true 
18:30:14:905 Debug: virtual void GrabberBase::startGrabbing() GrabberBase 
18:30:14:905 Debug: void MoodLampManager::start(bool) false 
18:30:14:905 Debug: void LightpackApplication::startPluginManager() 
18:30:14:905 Debug: static QString SettingsScope::Settings::getApplicationDirPath() "/home/[REDACTED]/.Prismatik/" 
18:30:14:905 Debug: void PluginsManager::LoadPlugins(QString) "/home/[REDACTED]/.Prismatik/Plugins" 
18:30:14:905 Debug: void PluginsManager::StartPlugins() 
18:30:14:905 Debug: void SettingsWindow::updateUiFromSettings() 
18:30:14:905 Debug: static QStringList SettingsScope::Settings::findAllProfiles() 
18:30:14:905 Debug: void SettingsWindow::profilesLoadAll() found profiles: ("Lightpack") 
18:30:14:905 Debug: static Lightpack::Mode SettingsScope::Settings::getLightpackMode() 
18:30:14:905 Debug: void SettingsWindow::onLightpackModeChanged(Lightpack::Mode) 0 0 
18:30:14:905 Debug: void LightpackApplication::showLedWidgets(bool) false 
18:30:14:905 Debug: void GrabManager::setVisibleLedWidgets(bool) false 
18:30:14:905 Debug: void LightpackApplication::setStatusChanged(Backlight::Status) 1 
18:30:14:905 Debug: void LightpackApplication::startBacklight() m_backlightStatus = 1 m_deviceLockStatus = 0 
18:30:14:905 Debug: static void SettingsScope::Settings::setIsBacklightEnabled(bool) 
18:30:14:905 Debug: static Lightpack::Mode SettingsScope::Settings::getLightpackMode() 
18:30:14:905 Debug: void GrabManager::start(bool) true 
18:30:14:905 Debug: virtual void GrabberBase::startGrabbing() GrabberBase 
18:30:14:905 Debug: void MoodLampManager::start(bool) false 
18:30:14:905 Warning: void LightpackApplication::startBacklight() status contains crap = 1 
18:30:14:905 Debug: static void SettingsScope::Settings::setKeepLightsOnAfterExit(bool) 
18:30:14:905 Debug: static void SettingsScope::Settings::setKeepLightsOnAfterLock(bool) 
18:30:14:905 Debug: void SettingsWindow::onPingDeviceEverySecond_Toggled(bool) true 
18:30:14:905 Debug: static void SettingsScope::Settings::setPingDeviceEverySecond(bool) 
18:30:14:905 Debug: static int SettingsScope::Settings::getGrabSlowdown() 
18:30:14:905 Debug: void SettingsWindow::onGrabSlowdown_valueChanged(int) 50 
18:30:14:905 Debug: static void SettingsScope::Settings::setGrabSlowdown(int) 
18:30:14:905 Debug: virtual void LedDeviceLightpack::setSmoothSlowdown(int) 100 
18:30:14:905 Debug: void SettingsWindow::onLuminosityThreshold_valueChanged(int) 3 
18:30:14:905 Debug: static void SettingsScope::Settings::setLuminosityThreshold(int) 
18:30:14:905 Debug: static bool SettingsScope::Settings::isMoodLampLiquidMode() 
18:30:14:905 Debug: static bool SettingsScope::Settings::isMoodLampLiquidMode() 
18:30:14:905 Debug: void SettingsWindow::onMoodLampLiquidMode_Toggled(bool) true 
18:30:14:905 Debug: static void SettingsScope::Settings::setMoodLampLiquidMode(bool) 
18:30:14:905 Debug: void MoodLampManager::setLiquidMode(bool) true 
18:30:14:905 Debug: static bool SettingsScope::Settings::isMoodLampLiquidMode() 
18:30:14:905 Debug: static QColor SettingsScope::Settings::getMoodLampColor() 
18:30:14:905 Debug: virtual void LedDeviceLightpack::requestFirmwareVersion() 
18:30:14:905 Debug: static void SettingsScope::Settings::setMoodLampColor(QColor) "#00ff00" 
18:30:14:905 Debug: bool LedDeviceLightpack::readDataFromDevice() 
18:30:14:905 Debug: static int SettingsScope::Settings::getMoodLampSpeed() 
18:30:14:905 Debug: virtual void LedDeviceLightpack::requestFirmwareVersion() Version: "7.6" 
18:30:14:905 Debug: void SettingsWindow::onMoodLampSpeed_valueChanged(int) 50 
18:30:14:906 Debug: static void SettingsScope::Settings::setMoodLampSpeed(int) 
18:30:14:906 Debug: void MoodLampManager::setLiquidModeSpeed(int) 50 
18:30:14:906 Debug: void SettingsWindow::onDeviceRefreshDelay_valueChanged(int) 100 
18:30:14:906 Debug: static void SettingsScope::Settings::setDeviceRefreshDelay(int) 
18:30:14:906 Debug: virtual void LedDeviceLightpack::setRefreshDelay(int) 100 
18:30:14:906 Debug: void SettingsWindow::onDeviceColorDepth_valueChanged(int) 128 
18:30:14:906 Debug: static void SettingsScope::Settings::setDeviceColorDepth(int) 
18:30:14:906 Debug: void SettingsWindow::onDeviceGammaCorrection_valueChanged(double) 2 
18:30:14:906 Debug: static void SettingsScope::Settings::setDeviceGamma(double) 
18:30:14:906 Debug: void SettingsWindow::onSliderDeviceGammaCorrection_valueChanged(int) 200 
18:30:14:906 Debug: static void SettingsScope::Settings::setDeviceGamma(double) 
18:30:14:906 Debug: void SettingsWindow::onListenOnlyOnLoInterface_Toggled(bool) true 
18:30:14:906 Debug: static void SettingsScope::Settings::setListenOnlyOnLoInterface(bool) 
18:30:14:906 Debug: virtual void LedDeviceLightpack::setColorDepth(int) 128 
18:30:14:906 Debug: void ApiServer::apiServerSettingsChanged() 
18:30:14:906 Debug: void SettingsWindow::onLoggingLevel_valueChanged(int) 1 
18:30:14:906 Debug: void ApiServer::stopListening() 
18:30:14:906 Debug: static void SettingsScope::Settings::setDebugLevel(int) 
18:30:14:906 Debug: static Grab::GrabberType SettingsScope::Settings::getGrabberType() 
18:30:14:906 Debug: void SettingsWindow::onMoodLampLiquidMode_Toggled(bool) true 
18:30:14:906 Debug: void ApiServer::startListening() 3636 
18:30:14:906 Debug: static void SettingsScope::Settings::setMoodLampLiquidMode(bool) 
18:30:14:906 Debug: void MoodLampManager::setLiquidMode(bool) true 
18:30:14:906 Debug: static bool SettingsScope::Settings::isMoodLampLiquidMode() 
18:30:14:906 Debug: void SettingsWindow::updateDeviceTabWidgetsVisibility() 
18:30:14:906 Debug: void SettingsWindow::setDeviceTabWidgetsVisibility(DeviceTab::Options) 63 
18:30:14:906 Debug: void SettingsWindow::settingsProfileChanged_UpdateUI(const QString&) 
18:30:14:906 Debug: static QStringList SettingsScope::Settings::findAllProfiles() 
18:30:14:907 Debug: virtual void LedDeviceLightpack::requestFirmwareVersion() 
18:30:14:907 Debug: bool LedDeviceLightpack::readDataFromDevice() 
18:30:14:907 Debug: virtual void LedDeviceLightpack::requestFirmwareVersion() Version: "7.6" 
18:30:14:930 Debug: int main(int, char**) thread id:  0x7fcd1566c740 
18:30:14:930 Debug: Start main event loop: lightpackApp.exec(); 
18:30:14:936 Debug: virtual void GrabberBase::setGrabInterval(int) GrabberBase 
18:30:14:937 Debug: void SettingsWindow::ledDeviceFirmwareVersionResult(const QString&) "0.0" 
18:30:14:937 Debug: void SettingsWindow::setFirmwareVersion(const QString&) 
18:30:14:937 Debug: void SettingsWindow::versionsUpdate() 
18:30:14:937 Debug: void SettingsWindow::updateDeviceTabWidgetsVisibility() 
18:30:14:937 Debug: void SettingsWindow::setDeviceTabWidgetsVisibility(DeviceTab::Options) 63 
18:30:14:937 Debug: void SettingsWindow::ledDeviceOpenSuccess(bool) true 
18:30:14:937 Debug: void SettingsWindow::updatePlugin(QList<Plugin*>) 
18:30:14:937 Debug: void LightpackPluginInterface::updatePlugin(QList<Plugin*>) 
18:30:14:944 Debug: void GrabManager::onGrabSlowdownChanged(int) 50 
18:30:14:944 Debug: virtual void GrabberBase::setGrabInterval(int) GrabberBase 
18:30:14:944 Debug: void SettingsWindow::ledDeviceFirmwareVersionResult(const QString&) "7.6" 
18:30:14:944 Debug: void SettingsWindow::setFirmwareVersion(const QString&) 
18:30:14:944 Debug: void SettingsWindow::versionsUpdate() 
18:30:14:944 Debug: void SettingsWindow::updateDeviceTabWidgetsVisibility() 
18:30:14:944 Debug: void SettingsWindow::setDeviceTabWidgetsVisibility(DeviceTab::Options) 63 
18:30:14:944 Debug: void SettingsWindow::ledDeviceOpenSuccess(bool) true 
18:30:14:944 Debug: void SettingsWindow::ledDeviceFirmwareVersionResult(const QString&) "7.6" 
18:30:14:944 Debug: void SettingsWindow::setFirmwareVersion(const QString&) 
18:30:14:945 Debug: void SettingsWindow::versionsUpdate() 
18:30:14:945 Debug: void SettingsWindow::updateDeviceTabWidgetsVisibility() 
18:30:14:945 Debug: void SettingsWindow::setDeviceTabWidgetsVisibility(DeviceTab::Options) 63 
18:30:14:992 Debug: virtual void GrabberBase::grab() reallocating`

[YouTube](https://youtu.be/Mfnd55OBkuY) video of above.

**Comment by psieg** [comment] 2016-05-03 11:16
Is this only since 5.11.2.7 or has this always been a problem?

**Comment by lauren-elise-thomas** [comment] 2016-05-04 21:51
I have only tried your version 5.11.2.7, 5.11.2.6, and official Prismatik 5.11.2. I just switched from Windows, so I haven't tested on other versions of Ubuntu.

I can try more configurations and post logs if you'd like.

**Comment by psieg** [comment] 2016-05-05 21:50
And none of the above works? I don't have an ubuntu machine, so I'll see if I can find the time to do it in a VM

**Comment by lauren-elise-thomas** [comment] 2016-05-26 00:50
I tried those three binaries all and none of the above works

**Comment by psieg** [comment] 2016-05-26 17:22
By default, when the platform supports tray icons, Prismatik does not open the window because you can open it through the tray if needed - theoretically. There have been some issues with unity in the past, but they should be fixed.
Does https://askubuntu.com/questions/155545/how-do-i-get-qsystemtrayicon-to-show-up-in-gnome-3 explain the problem? Which Qt version are you using?

**Comment by lauren-elise-thomas** [comment] 2016-05-27 00:25
The log from when I start Prismatik on the command line says Qt version currently in use: 5.5.1 18:30:14:697. I am not sure if that is the version Prismatik is using, but I just have a regular old Ubuntu 16.04 installation. I didn't upgrade from a previous release. I already have sni-qt installed but neither the appindicator or the window appear no matter how I launch Prismatik.

**Comment by Tidone** [comment] 2016-05-27 14:54
I think the problem is that the pre-built package of prismatik was not built for Unity. If you donwload the source code and build it yourself it should work with Ubuntu (at least that worked for me).

If you build it under Ubuntu the QT-Makefile (src.pro) includes a specific definition (UNITY_DESKTOP) and uses libappindicator instead of QT's own indicator, which is not supported by Unity.

I've run some tests with different Desktop Environments to see which indicator is needed
("with lai" means that the Makefile has to be changed to use libappindicator, more infos below):
.) KDE works without lai
.) MATE only works with lai
.) Unity only works with lai
.) LXDE works with and without lai
.) XFCE works with and without lai
.) GNOME does not work (I could not get it to work either way)

I changed src.pro the following way:
I copied the section which evaluates the desktop environment ("equals (DESKTOP, "Unity"){ DEFINES += UNITY_DESKTOP ...}) 3 times and changed the "Unity" to "MATE", "LXDE" and "XFCE", respectively.
This should take care of the most popular environments.
For LXDE and XFCE you don't have to do that if you want the better-looking indicator, because the libappindicator one is missing the icons.

@psieg: Could you change the Makefile to include the missing cases? Maybe you know a better method to determine which indicator has to be used?

**Comment by psieg** [comment] 2016-05-29 16:49
All of that should not be necessary after https://wiki.qt.io/New_Features_in_Qt_5.5:

> On supported desktops, the xcb plugin now uses the D-Bus based org.kde.StatusNotifier protocol for system tray icons, and org.freedesktop.Notifications for notifications. 


I will update my build system to build with 5.5 and we will see

> Debug: Build with Qt verison: 5.2.1 18:30:14:697
> Debug: Qt version currently in use: 5.5.1

**Comment by psieg** [comment] 2016-05-29 23:09
please try this build: https://psieg.de/jenkins/job/Prismatik_Linux/90/artifact/Software/dist_linux/prismatik_5.11.2.7_amd64.deb let me know whether it works

**Comment by lauren-elise-thomas** [comment] 2016-05-29 23:13
That build still doesn't work for me. I will redo my Ubuntu installation soon.

**Comment by Tidone** [comment] 2016-05-30 18:21
It doesn't work for me either.
It also still says that it was built with version 5.2.1.

I don't think it will work even if you switch to version 5.5 because I was using version 5.5.1 when I did the tests.

**Comment by psieg** [comment] 2016-05-31 21:44
This is obviously a known issue:
https://bugs.launchpad.net/appmenu-qt5/+bug/1574699
https://bugs.launchpad.net/ubuntu/+source/owncloud-client/+bug/1573639
This [workaround](https://github.com/owncloud/client/pull/4747) doesn't seem to be working tough.

I don't think adjusting the qmake file will help, as it only considers the build system's environment. A binary package should work on all OSes it is designed for.

**Comment by psieg** [comment] 2017-03-25 13:45
seems to be fixed in newer Qt versions, re-enabled the icon in 4ae663d9670e157ff006a5a611f76d1b70977107

**Closed by psieg** 2017-03-25 13:45 UTC
