### ISSUE TITLE
Active mode resets to screen capture on every reboot

### ISSUE THREAD

**Issue by Razunter** [psieg/Lightpack#65] opened 2016-07-22 08:22 UTC
Active mode resets to screen capture on every reboot.
I have to reset lights mode to "simple lights" every time I reboot my computer. I don't know if it's bug in last Prismatik version or something changed in Windows...

System: Windows 10 x64
Software: 5.11.2.9
Firmware: 7.6+1

**Comment by psieg** [comment] 2016-07-23 19:16
Do other settings persist? Please try quitting and restarting Prismatik - does that also lose the setting?
You can try checking whether the profile file is marked read-only.

**Comment by Razunter** [comment] 2016-07-23 19:24
Other settings persist. Restarting leads to same mode switch. Not read-only.
Settings & logs: https://dl.dropboxusercontent.com/u/103461/temp/Prismatik.zip
First log after exit with proper mode selected.

**Comment by psieg** [comment] 2016-07-23 20:34
hm, I'm not sure what's happening. I cannot reproduce it on my machine. Can you rerun the scenario but increase the log level to 2 first?

**Comment by Razunter** [comment] 2016-07-23 20:36
New logs: https://dl.dropboxusercontent.com/u/103461/temp/Prismatik_2.zip

**Comment by psieg** [comment] 2016-07-23 20:42
Got it. It's related to the language switching. You can trigger it by manually switching the language. I'll fix it when I have time.
Workaround for now should be to switch to System language (?)

**Comment by psieg** [comment] 2016-07-27 21:38
Fixed in 4f1100a765238fe5d0eca3b188d2c12b68725126

**Closed by psieg** 2016-07-27 21:38 UTC
