### ISSUE TITLE
Perfomance problem on Mac os Mojave

### ISSUE THREAD

**Issue by Kaitoukid93** [psieg/Lightpack#211] opened 2018-11-28 15:08 UTC
Hello. Im a big fan of Ambilight devices
Back in the day when I was usung mac os Yosemite. Prismatik software worked perfectly without lagging issues
Now I have my new Macbook with the  lastest version of unofficial prismatik installed, I faced the lagging issues, my system completely slowdown when turn on screen grabbing mode. The CPU usage is not too high and the same to GPU
Does anyone or just me have this lagging issues?
Please show me a way to fix this
thanks

Macbook pro 15 inch 2016
2.6Ghz intel core i7
Radeon pro 450 2Gb+ intel HD Graphic530

**Comment by psieg** [comment] 2018-12-09 17:33
Duplicate of #210

**Closed by psieg** 2018-12-09 17:33 UTC
