### ISSUE TITLE
High CPU usage after switching display

### ISSUE THREAD

**Issue by Dawider10** [psieg/Lightpack#181] opened 2018-04-14 20:57 UTC
I've got one monitor connected to two graphics cards in one PC. After switching between them (internal/external option in Win+P menu), Lightpack Software starts to use ~22% of CPU (OC'ed i5-6600K).
It returns to normal when I manually restart Prismatik or switch to previously selected display (GPU).
Maybe you could implement a feature which would restart Prismatik after switching display?

**Comment by psieg** [comment] 2018-04-17 16:25
Hi,
this sounds like a bug. Rather than restarting Prismatik, I'd like to fix the bug. Could you please turn up the log level in expert settings and post it here (`C:\Users\YourName\Prismatik\Logs\`)?

**Comment by Dawider10** [comment] 2018-04-17 19:39
Unfortunately, at the moment, I'm no able to initiate this bug because I changed my PC setup. I'll be able to do it approximately in a month or two. I've got some logs in this folder right now. [Link](https://1drv.ms/f/s!AhgQNTsP2SVFjTd0IphpKSnwwoxQ)

I didn't explain well what's on my mind. I suggested you this feature because now I have to manually restart Prismatik every time I switch display to make it work. It would be nice if you could resolve this in some way. Unless it's the fault of this bug.

**Comment by UrbanCMC** [comment] 2018-04-22 07:47
I can confirm what I hope to be the same thing happening in a much simpler scenario.  

I have two displays connected to my PC, which is normally set to "Extend". Changing this to any other mode causes ~10% CPU usage until I change it back, after which everything returns to normal.  

The relevant section in the [log file](https://github.com/psieg/Lightpack/files/1935303/Prismatik.0.zip) is from 09:27:52 to 09:28:14, during which the following two lines are logged repeatedly:
`09:27:52:038 Critical: bool __cdecl DDuplGrabber::_reallocate(const class QList<struct ScreenInfo> &) Failed to duplicate output: 0x887A0025`
`09:27:52:047 Critical: void __cdecl GrabberBase::grab(void)  couldn't reallocate grabbing buffer`

**Comment by psieg** [comment] 2018-04-25 14:50
@Dawider10 your logs show device errors:
`16:33:06:296 Warning: void __cdecl LedDeviceAdalight::open(void) Serial device "COM20" open fail.  "No such file or directory"`
So things should not work at all because the device cannot be accessed.

@UrbanCMC the error code means "An on-going mode change prevented completion of the call. The call may succeed if attempted later." I was able to reproduce it once and created a fix, but now I can't reproduce...

**Comment by Dawider10** [comment] 2018-04-25 15:16
@psieg I probably had the device disconnected, that's why this error appeared. As I said I was working with my PC setup so some devices were disconnected like this one. Everything is working well except when I switch the display. Then CPU usage jumps and I have to restart Prismatik to return things to normal.

**Comment by Dawider10** [comment] 2018-04-25 15:44
I managed to reproduce this bug again. [Log](https://1drv.ms/u/s!AhgQNTsP2SVFjUGxoHWz2pmiW7sG)
Here is what I've done during this reproduction:
1. Launch Prismatik and turn it on if it was turned off
2. Move something on the screen
3. Change the display (High CPU usage starts here [17:31:45])
4. Move something on the screen
5. Quit Prismatik

**Comment by psieg** [comment] 2018-04-26 07:43
You seem to have 3 dedicated GPUs. Are you running a surround setup?

Can you please describe your setup in detail, i.e. which display is connected to which GPU (do you use the internal one) and which modes exactly are you switching between? On which screen are the grab widgets?

**Comment by psieg** [comment] 2018-04-26 07:47
also, does it happen with WinAPI grabbing mode?

**Comment by Dawider10** [comment] 2018-04-26 11:08
No, I'm not running a surround setup.

Sure. One display is connected to both #1 dedicated GPU and iGPU. The other two dedicated GPU's are not connected to any display. As I described in the first post, I'm switching between 'internal' and 'external' display modes. There is only one display and I'm just switching between these two connected GPU's.

It doesn't happen when I use WinAPI grabbing mode. I can switch between displays and Prismatik is working perfectly fine.

**Comment by psieg** [comment] 2018-04-26 15:15
Should be fixed in 5.11.2.17. Please reopen if it still happens

**Closed by psieg** 2018-04-26 15:15 UTC
Labels: confirmed bug
