### ISSUE TITLE
Desktop duplication bug on Windows 10

### ISSUE THREAD

**Issue by olafnew** [psieg/Lightpack#81] opened 2016-10-11 01:04 UTC
Good day!
Struggling, as getting severe problems on my Windows 10 PC. (Win 10 x64 10.0.14393 N/A Build 14393; nvidia 970 driver 373.06).

When turning on desktop duplication - all my overlays(?), such as right click on the menu, highlighting options in windows native applications, and other things - are acting extremely weird. I really do not know how to describe it well enough - that is why i composed a small video really well describing this bug. Pls see the link below https://youtu.be/9z6sgoh1hsc 

I don't really understand how to create logs - if there is a possibility to create logs, i will gladly do so, i just need a bit of info on how to create logs... As i see no options for logging, and can't really figure out a way to generate logs...

**Comment by psieg** [comment] 2016-10-13 09:28
A really interesting issue, I have not seen such behavior yet.
Prismatik writes logs to `C:\Users\YourName\Prismatik\Logs`. You can increase the log level in the experimental settings.

Can you try [this sample application](https://github.com/psieg/Lightpack/files/444647/DesktopDuplication.zip) and see whether the problem occurs? This should help narrow down the source. The app is [a microsoft sample](https://code.msdn.microsoft.com/windowsdesktop/Desktop-Duplication-Sample-da4c696a) if you want to build it yourself.

**Comment by olafnew** [comment] 2016-10-17 19:26
Tested the application based on the MS Example - no such behavior occurs. No matter what i try - the duplication example works flawlessly.

I've included a log file, maximum logging depth (3), but no real mess i can see there. Could you please specify  - where to look further, to help and be more accurate on pinpointing the issue?
[Prismatik.1.zip](https://github.com/psieg/Lightpack/files/534487/Prismatik.1.zip)

**Comment by psieg** [comment] 2016-10-21 14:42
I currently have no clue what might cause the issue, so let's just rule out some factors:

- I see you are using an Ambilight device. Please backup your config and try to reproduce the issue with a virtual device. Does it happen in that case?
- Try running without admin privileges - does it happen?

**Comment by psieg** [comment] 2017-08-26 11:02
Closing this due to lacking feedback.

**Closed by psieg** 2017-08-26 11:02 UTC
Labels: awaiting feedback
