### ISSUE TITLE
Increase number of allowed LEDs for Adalight

### ISSUE THREAD

**Issue by formtapez** [psieg/Lightpack#169] opened 2018-03-17 22:49 UTC
Hello,
can you please increase the maximum number of allowed LEDs for the Adalight driver?
I have 266 LEDs, but in setup wizard the value is limited to 255 👎

And please add "1.000.000" (1 MBaud) to the Baud-Rate selector.

**Comment by psieg** [comment] 2018-03-19 16:10
Duplicate of #148

**Closed by psieg** 2018-03-19 16:10 UTC
