### ISSUE TITLE
Weird behavior with "Keep lights ON after lock computer" option

### ISSUE THREAD

**Issue by Kelvets** [psieg/Lightpack#58] opened 2016-06-24 21:31 UTC
First, I must say I'm using a Lightpack clone I got from eBay, so perhaps the issue is not with the software itself, but how it interacts with this clone's firmware. Just in case it's a software issue that happens with the regular lightpack too and has remained undetected, I'm posting it.

When the "Keep lights ON after lock computer" option is NOT checkmarked and I lock my computer while the lights are OFF, upon typing my password back again, the lights will turn ON on their own, but that won't be reflected in Prismatik. So to turn them OFF again, I'll have to right-click the icon, turn them on and turn them off.

Interestingly, even if I sleep or hibernate the computer, the glitch will still happen when the "Keep lights ON after lock computer" is NOT checkmarked, even though it's supposed to control locking and not sleeping/hibernating (which I guess should be ruled by the second option, the "suspend" one instead).

The problem goes away when I checkmark the "Keep lights ON after lock computer" option. That is, if the lights were off before locking/sleeping/hibernating, they will remain off upon logging into Windows again, even though the option says they should be turned on!

**Comment by psieg** [comment] 2016-06-25 15:00
> The problem goes away when I checkmark the "Keep lights ON after lock computer" option. That is, if the lights were off before locking/sleeping/hibernating, they will remain off upon logging into Windows again, even though the option says they should be turned on!
This is as designed, since the option says to *keep* them on if they are on, not *turn* them on.

However I never considered the case where they would be manually switched off in my testing, which is the issue here

**Comment by Kelvets** [comment] 2016-06-25 18:23
You also said something similar on Reddit... what's so weird about wanting to disable the lights so as to not disturb roommates trying to sleep, or to use a stronger lamp-based backlight, etc?

Anyway, you'll fix this, right? :)

**Comment by psieg** [comment] 2016-06-26 19:36
It's just not one of the use cases I had in mind. If a roommate is trying to sleep, the screen will be an issue too, and I always found the lights way bright enough.
But sure, this is a bug and I'll fix it next time I get a chance

**Comment by psieg** [comment] 2016-07-09 17:25
Fixed in 099b6e75dc8105000b9d8c262ee56f08b7bba740, will be included in the next release

**Closed by psieg** 2016-07-09 17:25 UTC

**Comment by Kelvets** [comment] 2016-07-09 18:23
Awesome! Wanna PM me your PayPal or something so I can buy you a beer for all your continuing work?

**Comment by psieg** [comment] 2016-07-23 20:46
Will do once the next release is out and you get to enjoy the fix :P
