### ISSUE TITLE
Gamma ramp feature doesn't work with more than one monitor connected

### ISSUE THREAD

**Issue by jlapthorne** [psieg/Lightpack#127] opened 2017-06-20 13:34 UTC
With 3 monitors connected, the backlight remains bright white regardless of f.lux setting.
After disabling all but one, the features works as expected.

**Comment by psieg** [comment] 2017-07-19 15:57
Indeed. There should be an easy fix but it requires messing with the windows API. I'll do it next time I get around to spending time on Prismatik.

**Comment by psieg** [comment] 2017-08-16 18:49
Hey,

since the issue is fixed on master but the next release is some time away, you can use this dirty/inofficial version for now:

https://psieg.de/jenkins/job/Prismatik_Windows/lastSuccessfulBuild/artifact/Software/dist_windows/Output/Prismatik%20(unofficial)%2064bit%20Setup%205.11.2.13.exe

**Comment by jlapthorne** [comment] 2017-08-17 00:41
Tested and working! Thanks

**Comment by johnmrushing** [comment] 2017-12-06 07:08
Can't get integration to work on single/multiple monitors on either stable or 205.11.2.13. "Apply screen color modifications" checkbox doesn't appear to change anything. Is the issue perhaps with flux?

I've tried uninstalling and reinstalling both flux and prismatik, as well as setting up a whole new profile for the lightpack.

Any ideas what I'm missing?

**Comment by johnmrushing** [comment] 2017-12-06 07:12
Tried reinstalling both flux and prismatik, using both versions of prismatik (stable, and the one above)0. I can't get the "apply screen color modifications" to work regardless of how many monitors I'm using.

Any ideas what I'm missing?

**Comment by psieg** [comment] 2017-12-06 23:11
Have you used the "extend color range" option in flux?

**Comment by johnmrushing** [comment] 2017-12-07 02:16
I didn't. Must've missed that in the documentation. Enabled it and now it works. Awesome!!! Thanks!

**Closed** 2018-03-20 22:26 UTC
Labels: confirmed bug

**Comment by johnmrushing** [comment] 2018-07-02 03:15
Something broke. Running

Priskmatik (unofficial): software 5.11.2.17 (revision 1863b15f)
f.lux: version 4.75

Now lights no longer implement color modifications.

If tied to #190, can roll back for troubleshooting data, but would rather not do so unnecessarily.
