### ISSUE TITLE
Prismatik crashes after resuming from Sleep/Standby mode in Windows 7 x64

### ISSUE THREAD

**Issue by soulhunter123** [psieg/Lightpack#85] opened 2016-12-07 23:59 UTC
As per the title, whenever I use "Sleep" on Windows 7 x64, Prismatik crashes upon resuming Windows.

There's no error message; the icon just disappears when moused over and the lights don't work.

**Comment by psieg** [comment] 2016-12-11 20:52
Can you check the logs at `C:\Users\You\Prismatik\Logs` please? What are the last few lines?
Does it happen every time you sleep/resume? Is the Lightpack powered during sleep?

**Comment by DjFIL007** [comment] 2016-12-18 05:14
I have same issue with Win 10 x64.  90% of the time I lock my computer, which resutls in the lights turning off before the computer fully goes to sleep.  Here's the last section of an earlier log that clearly shows sleep/resume...

`Session is locking
10:42:05:577 Debug: void __cdecl LedDeviceLightpack::switchOffLeds(void)
10:42:05:578 Debug: void __cdecl LedDeviceLightpack::switchOffLeds(void)
11:36:53:189 Debug: bool __cdecl SessionChangeDetector::nativeEventFilter(const class QByteArray &,void *,long *) System is going to sleep
11:36:53:189 Debug: void __cdecl LedDeviceLightpack::switchOffLeds(void)
15:12:05:135 Debug: bool __cdecl SessionChangeDetector::nativeEventFilter(const class QByteArray &,void *,long *) System is resuming
15:12:05:136 Warning: QObject::startTimer: Timers cannot be started from another thread
15:12:05:151 Debug: void __cdecl LedDeviceLightpack::updateDeviceSettings(void) LedDeviceManager(0x1d72f7f5470)
15:12:05:744 Debug: void __cdecl LedDeviceLightpack::setUsbPowerLedDisabled(bool) false
15:12:05:745 Debug: void __cdecl LedDeviceLightpack::setRefreshDelay(int) 100
15:12:05:746 Debug: void __cdecl LedDeviceLightpack::setColorDepth(int) 128
15:12:05:754 Debug: void __cdecl LedDeviceLightpack::setSmoothSlowdown(int) 100
15:12:05:756 Debug: void __cdecl LedDeviceLightpack::requestFirmwareVersion(void)
15:12:05:756 Debug: bool __cdecl LedDeviceLightpack::readDataFromDevice(void)
15:12:05:756 Debug: void __cdecl LedDeviceLightpack::requestFirmwareVersion(void) Version: "7.5"
15:12:05:756 Debug: void __cdecl SettingsWindow::ledDeviceFirmwareVersionResult(const class QString &) "7.5"
15:12:05:756 Debug: void __cdecl SettingsWindow::setFirmwareVersion(const class QString &)
15:12:05:756 Debug: void __cdecl SettingsWindow::versionsUpdate(void)
15:12:05:756 Debug: void __cdecl SettingsWindow::updateDeviceTabWidgetsVisibility(void)
15:12:05:757 Debug: void __cdecl SettingsWindow::setDeviceTabWidgetsVisibility(enum DeviceTab::Options) 63
15:12:05:757 Debug: int __cdecl SettingsWindow::getLigtpackFirmwareVersionMajor(void) Prismatik major version: 7
15:12:05:757 Debug: void __cdecl SettingsWindow::ledDeviceFirmwareVersionUnofficialResult(const int) 0
15:12:09:797 Debug: bool __cdecl SessionChangeDetector::nativeEventFilter(const class QByteArray &,void *,long *) Session is unlocking
15:12:09:797 Debug: bool __cdecl SessionChangeDetector::nativeEventFilter(const class QByteArray &,void *,long *) Session is unlocking
15:21:31:890 Debug: bool __cdecl SessionChangeDetector::nativeEventFilter(const class QByteArray &,void *,long *) Session is locking
15:21:31:890 Debug: bool __cdecl SessionChangeDetector::nativeEventFilter(const class QByteArray &,void *,long *) Session is locking
15:21:31:891 Debug: void __cdecl LedDeviceLightpack::switchOffLeds(void)
15:21:31:892 Debug: void __cdecl LedDeviceLightpack::switchOffLeds(void)
15:51:58:754 Debug: bool __cdecl SessionChangeDetector::nativeEventFilter(const class QByteArray &,void *,long *) System is going to sleep
15:51:58:754 Debug: void __cdecl LedDeviceLightpack::switchOffLeds(void)
17:43:06:779 Debug: bool __cdecl SessionChangeDetector::nativeEventFilter(const class QByteArray &,void *,long *) System is going to sleep
17:43:06:779 Debug: void __cdecl LedDeviceLightpack::switchOffLeds(void)
17:44:40:117 Debug: bool __cdecl SessionChangeDetector::nativeEventFilter(const class QByteArray &,void *,long *) Session is ending
17:44:40:118 Debug: void __cdecl LedDeviceLightpack::switchOffLeds(void)
`

**Comment by psieg** [comment] 2017-01-18 09:19
Hi guys,

is this still an issue? If so, can you please check the windows event log for details on the crash?
It seems not a single log entry is written after the resume, is that correct?

**Comment by soulhunter123** [comment] 2017-01-21 22:34
For me it is, although I haven't updated Prismatik since my original post.

Error data:

```
Faulting application name: Prismatik.exe, version: 5.11.2.11, time stamp: 0x580a4cb3
Faulting module name: ntdll.dll, version: 6.1.7601.18247, time stamp: 0x521eaf24
Exception code: 0xc0000005
Fault offset: 0x000000000001863b
Faulting process id: 0xbe4
Faulting application start time: 0x01d2741a57807f15
Faulting application path: D:\Program Files\Prismatik\Prismatik.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: d98f0b1c-e028-11e6-beee-d017c2ab94dc
```

**Comment by psieg** [comment] 2017-02-07 17:39
@soulhunter123 I assume all log entries are before the compupter sleeps. Is this on maximum log level?
@DjFIL007 Your logs also show the resume entries, up until session termination (logout or shutdown). When did it crash?

Unfortunately, I cannot reproduce this.

**Comment by psieg** [comment] 2017-08-26 11:02
Closing this due to lacking feedback.

**Closed by psieg** 2017-08-26 11:02 UTC
Labels: awaiting feedback
