### ISSUE TITLE
Prismatik 5.11.2.13 maps screen to led strip not correctly on MacBook Pro 15" 2017

### ISSUE THREAD

**Issue by ShtokyD** [psieg/Lightpack#162] opened 2018-03-02 13:04 UTC
Hi! I made Adalight backlight for my MacBook but seems like Prismatik 5.11.2.13 maps MacBook Pro 15" 2017 2880x1800 221 ppi screen to strip led not correctly. OS - High Sierra 10.13.3. I use Adalight device, Arduino Nano with Atmega 326P chip, 78 leds WS2812B/SK6812 strip. During device configuration wizard all 78 leds widgets are placed correctly along the screen edges but have wrong sizes, they don't match the MacBook screen size. So I get only a part of the screen mapped for all 78 leds - 1680x1056px - the top left corner of the screen, and this part is sort of duplicated to the right side of the screen, so in the middle of the screen I get left and right edges of the led strip mapped. But if I manually set all 78 leds widgets to proper sizes regarding my 2880x1800px screen these widgets do not display within my screen anymore during device configuration wizard and I get only top left corner on the strip mapped. So it would be really great to have a monitor size setup screen in device configuration wizard to make Prismatik know what screen size it is working with. Hope you can fix it, thanks!

**Comment by psieg** [comment] 2018-03-09 09:53
duplicate of #79 
Sorry I'm not a Mac developer. Someone else needs to step up...

**Closed by psieg** 2018-03-09 09:53 UTC

**Comment by ShtokyD** [comment] 2018-03-10 13:34
Thanks for the reply and link, I fixed that by just changing monitor resolution on my MacBook, turned out that by default it was set to 1680x1050, so Prismatik captured that. But after changing it to full 2880x1800 in the monitor settings everything is working correctly now!
