### ISSUE TITLE
DDUPL and HDR creates lightning

### ISSUE THREAD

**Issue by sblantipodi** [psieg/Lightpack#355] opened 2020-06-09 13:52 UTC
Hi,
when using DDUPL and HDR in Window 10 my LEDs flashes from time to time.

It's like to have some lightning behing the monitor that flashes white.
If I switch to NVFBC no problem at all.

Any idea?
Thanks

**Comment by zomfg** [comment] 2020-06-09 13:58
duplicate of #255 ?

**Comment by sblantipodi** [comment] 2020-06-09 14:08
I can add some more infos to the issue.
I have a i7 5930K@4.2GHz 6 cores HEDT CPU with 32GB DDR4 and an RTX2080Ti.

With this system Prismatik can capture the screen from 24 to 28FPS.
If I set the grab interval to 33ms (because I would like to grab at 30FPS) prismatik produces flashes because the grabber can't achieve 30FPS. If I reduce the grab interval to 53ms flashes disappear.

I don't have this problem with NVFBC because with NVBFC grabber can grab at 33ms without problems.

This problem happens only when HDR is on.

**Closed** 2020-06-09 14:12 UTC
