### ISSUE TITLE
Support for two or more Displays

### ISSUE THREAD

**Issue by BlackX777** [psieg/Lightpack#287] opened 2020-01-11 16:12 UTC
I have two Monitors with Adalight + Arduino Nano
one for Gaming one for Movies with different LED Setups.
Proplem is the Profiles dont change the SerialPort (COM3 & COM4)
so I must everytime switch the main.conf .
I use Prismatik (unofficial) 5.11.2.19 with added NvFBC support :P
Running two different Instances at the same time also dont work respectively they use the same config.
Is it possible to implement support for more Adalights?

with best regards Toni

**Comment by psieg** [comment] 2020-01-17 18:31
Duplicate of #280

**Closed by psieg** 2020-01-17 18:31 UTC
