### ISSUE TITLE
Flux LED flickering

### ISSUE THREAD

**Issue by Domoer8** [psieg/Lightpack#158] opened 2017-12-26 07:31 UTC
When using f.lux I'm getting lots of sudden color darkening.  The entire array will flash deep red at random intervals. Works perfectly without the f.lux box checked.

**Comment by psieg** [comment] 2018-01-09 20:51
*Is there anything uncommon about your flux or Prismatik settings?
*Have you enabled the "extended" flux mode?
*To which level did you set flux? Does it happen with other levels?
*Which Capture source are you using?
*Can you increase the debug level and provide logs?

**Comment by psieg** [comment] 2018-03-12 11:32
Any Update? I'll have to close this if I don't hear back from you.

**Comment by Domoer8** [comment] 2018-03-14 07:09
Sorry, I was away from my setup for a month.  I noticed the color stuttering was due to a frame rate drop.  I did some experimenting and things have been much better.

- I changed my grab interval to 16ms.
- switched capture source to WinAPI (Fullscreen)
- changed my profile .ini files to be 'read only'

I think the main culprit was the capture source.
Occasionally my profiles would freak out and would be totally out of order.  Changing to 'read only' fixed that.  
Thanks for your patience!  Awesome product.

**Comment by psieg** [comment] 2018-03-15 18:04
Fixed by switching to WinAPI sounds wrong.
Are you sure it happens only if the f.lux setting is enabled?

**Comment by Dallas-J** [comment] 2018-03-18 03:00
I've run into the same issue - I even reinstalled f.lux, making sure that I did not enable extended mode. I can confirm that WinAPI does not have the same issue, but it locks my high refresh rate panel to 30Hz. Without the f.lux setting checked, the backlight doesn't flash but the colors are (expectedly) incorrect.

I did some testing on changing settings in f.lux; none of the settings change the flashing. I also tried using the new night mode in Windows 10, but whatever is used to pick up screen color modifications doesn't pick it up.

After further testing, I noticed that the color stuttering was due to the program not reaching the desired capture rate and dropping frames just as Domoer8 said. I'm guessing WinAPI's 30Hz lock is the reason that it fixes the issue, but I was able to fix this issue by turning my sample rate up to 20ms for now.

**Comment by psieg** [comment] 2018-03-19 16:16
There is a misunderstanding about the capture rate with Desktop Duplication. If the screen content does not change at a rate higher than or equal to the selected rate, the effective rate will be lower. This is intentional, as there is no point in capturing the same picture again - no frame is dropped.

Which device are you guys using? Is it maybe because the device expects new data every x ms? - This should be unrelated to the f.lux setting then...

**Comment by Dallas-J** [comment] 2018-03-19 19:57
I'm using an Arduino Uno and it is programmed to block until new data is received, but I won't rule that out just in case.

It is worth noting that when the image is static, no flickering occurred and no frames are dropped - I was thinking of frame drops as times when the program cannot keep up with the desired capture rate. If I set the desired sample rate to 16ms (60Hz), for instance, Prismatik's FPS counter will occasionally jump to 1000.0 and the LEDs will flash dark red. The reason I'm assuming that to be a frame drop is because it happens far more frequently if I change the sample rate to 10ms (100Hz) and stops if I change the sample rate to 20ms (50Hz).

Some other stuff about my setup in case it matters:
* Running 2560x1440 @ 120Hz with G-SYNC
* Using 253 RGBW LEDs with the NeoPixel library
* Baud rate is set to 2M, maximum for Arduino Uno

I'm interested to know if @Domoer8 has any similar hardware - maybe we both won the hardware lotto?

**Comment by dmadison** [comment] 2018-03-19 20:25
What driver code are you using on the Uno? And what device type in Prismatik? And what LED type (chipset)?

My hunch is that at the higher capture rates you're truncating serial data during the LED latch, and bad or channel-mismatched data is being pushed to the strip.

**Comment by Dallas-J** [comment] 2018-03-19 20:45
I translated the Adalight FastLED driver for use with NeoPixel devices since I could't find that myself - you can check it out [here](https://github.com/Dallas-J/NeoPixel-Adalight). I am using the Adalight device type in Prismatik with a Baud rate of 2M, and the LED chipset is sk6812.

**Comment by dmadison** [comment] 2018-03-19 21:41
Try adding a function to clear the serial buffer after each latch:

```c
while(Serial.available() > 0) {
	byte r = Serial.read();
}
```

I'd also try backing down the baud rate, counter-intuitive as that sounds.

I ran into a very similar problem when I was making my own DIY ambilight. The key issue is that the libraries used for the LED protocol disable interrupts, and thus you lose data during the LED latch. For WS2812B LEDs that's 30 µs per LED, and it's similar for the SK6812.

In the few microseconds it takes for the Arduino to switch gears from reading from the serial buffer to outputting the data to the strip, the serial interrupts keep functioning and saving data into the buffer. Now here's the rub: at high data rates, it's entirely possible to buffer the complete header for a new frame **without any of the associated color data**. When the loop is resumed for the next frame, the header is successfully parsed from the buffer and if the timing doesn't line up for the new data coming in you get a channel mismatch.

Prismatik is not entirely blameless, though. The grab rates are inconsistent (#120), and occasionally the software *will* hiccup and send a subsequent frame immediately rather than at the specified delay. Software flow control (#117) could also help, although it's not currently implemented.

I don't know if f.lux affects the grab rate inconsistencies or if it's just a coincidence. If you have a logic analyzer you could sniff the serial timing and see.

**Comment by Dallas-J** [comment] 2018-03-19 22:04
Interesting thoughts - my only remaining question is why everything would function normally without the f.lux color shift. I don't have a logic analyzer so that's out of the picture, but I'll check out the rest of what you said in a week or two (this is finals week at my university). Backing the baud rate down won't really show anything though, since a baud of 1M is barely enough to hold ~50Hz with 253 LEDs. Just to make sure the overall picture is clear here, Prismatik works great and I'm perfectly happy sticking with a 50Hz refresh rate as that is more than fast enough. I'd say this is a bit of an edge case - just thought I'd update the issue since I ran across the same thing.

**Comment by thesharkm4n** [comment] 2018-04-05 20:57
I'm getting the same issue on the official light-pack hardware. Like the others it does not occur for static images, and disappears on turning off the screen color modification setting or on reducing the grab rate.

The lightpack is set to the primary monitor 1080x1920, and i have a second monitor at 1680x1050 if that helps.

**Comment by psieg** [comment] 2018-04-05 21:01
I can't reproduce. What do you use for a non-static image?
Do all of you have two monitors?

**Comment by thesharkm4n** [comment] 2018-04-05 21:02
Even something as small as moving my mouse causes the image to flicker.

**Comment by Domoer8** [comment] 2018-04-05 21:06
Just one 3840x2160 monitor here.  Could it be my 4K resolution?

**Comment by thesharkm4n** [comment] 2018-04-05 21:06
Actually maybe my issue is slightly different. It only occurs on moving my mouse on the primary monitor.

**Comment by thesharkm4n** [comment] 2018-04-05 21:39
Here's a gif of whats going on with mine since its hard to explain 
https://gfycat.com/NaiveSilverFireant

**Comment by Dallas-J** [comment] 2018-04-06 07:56
https://photos.app.goo.gl/rAPrSKUBmUvxjYQI2

Here's a video of mine as well - Last time I checked in I was using a 1440p panel, but now I have switched screens temporarily to a 1080p one. Both are high refresh rate if that matters.

Switching to 1080p has also allowed me to get down to 16ms without the flickering, but I'd expect the effect to be reproducible on any system by changing the sample rate to 1ms. I'd say this is probably why the op noticed, since this seems to scale with resolution.

**Comment by psieg** [comment] 2018-04-06 08:11
Thanks all for the detailed information.

Without being able to reproduce, I believe the issue is that multiple screen grabs get queued. This leads to the color modifications being applied twice. I'll include what should be a fix for this in the .16 release.

**Comment by Domoer8** [comment] 2018-04-06 20:32
Awesome!  Any chance you could throw in a 'Restart' button above the 'Quit' button from the task bar menu?

**Comment by thesharkm4n** [comment] 2018-04-07 15:39
I can confirm that the latest update has fixed this for me! Thanks

**Comment by psieg** [comment] 2018-04-08 18:04
@Domoer8 please create a new issue and explain why you want that. It sounds like this is working around some other problem you're having?

**Closed by psieg** 2018-04-08 18:04 UTC
