### ISSUE TITLE
I think there might be is a workaround for plugins not working in your latest version!

### ISSUE THREAD

**Issue by anirudhlath** [psieg/Lightpack#139] opened 2017-10-12 06:28 UTC
I tried tweaking the animate plugin. There were few standalone errors which I fixed in this attached version. There are four types of animations in this file, I manually tried changing it and it worked perfectly as a standalone script, as in if I run the animate file directly by double-clicking it, it connects to your lightpack system, automatically recognises the order and number of LEDs and the animates the lightpack flawlessly. I think there might be some kind of interpreter problem with the new releases of the prismatik. You should consider comparing the plugins part of prismatik 5.9.6 and your release. And also, when I run the animate script, instead of conflicting with the prismatik software, the prismatik software shows the its controls are locked by the API server. I really really believe in you and I think you might fix this issue, because just screen grabbing all the time does not kinda work :P 
[Animate-master.zip](https://github.com/psieg/Lightpack/files/1378257/Animate-master.zip)

Thanks!
Anirudh Lath

**Comment by psieg** [comment] 2017-10-18 18:09
There is no interpreter whatsoever in later versions of Prismatik.
The old plugins can be migrated, yes. Basically all you need to do is install python and write a config file. For example, [this](https://github.com/owenb321/Animate) seems to be a working port of the Animate plugin.

**Comment by psieg** [comment] 2017-10-18 18:15
Also, duplicate of #126

**Closed by psieg** 2017-10-18 18:15 UTC
