### ISSUE TITLE
Screen grabbing moving from 1st monitor to 2nd

### ISSUE THREAD

**Issue by Dawider10** [psieg/Lightpack#141] opened 2017-10-15 21:35 UTC
I've configured Prismatik screen grabbing areas to be on the Monitor 1 (primary, with auto-sleep) but every time when I turn off Monitor 1 manually, they are moving to the Monitor 2 (secondary, without auto-sleep). Areas are not moving from Monitor 2 to Monitor 1 when I turn off Monitor 1.

**Comment by psieg** [comment] 2017-10-18 18:04
Duplicate of #140

**Closed by psieg** 2017-10-18 18:04 UTC
